### ISSUE TITLE
pyopencl error

### ISSUE THREAD

**Issue by alexxrobert** [ZigaMr/ReverseProfanityTool#1]
I get this error after runnning 2 minutes on a RTX 3090
Traceback (most recent call last):
  File "/root/ReverseProfanityTool/main.py", line 38, in <module>
    prof.run_kernel(addresses.address.to_list(), addresses.public_key.to_list())
  File "/root/ReverseProfanityTool/src/tools.py", line 32, in wrapper
    result = func(*args, **kwargs)
  File "/root/ReverseProfanityTool/src/tools.py", line 543, in run_kernel
    cl.enqueue_copy(self.queue, result_array, array_buf)
  File "/usr/local/lib/python3.9/site-packages/pyopencl/__init__.py", line 2013, in enqueue_copy
    return _cl._enqueue_read_buffer(queue, src, dest, **kwargs)
pyopencl._cl.RuntimeError: clEnqueueReadBuffer failed: OUT_OF_RESOURCES

**Comment by ZigaMr** [comment]
There might be some hardware or openCL limitations. The script loads 80% of available GPU memory with binary file data, so if you're using 24gb 3090 RTX there might be some limits. Try changing the 0.8 value, on line 19, to something smaller like 0.5 or 0.2.

**Comment by alexxrobert** [comment]
It worked with 0.3, maybe I dont get access to all memory(its machine from Vast.ai).
Now I get this error:
(sqlite3.IntegrityError) UNIQUE constraint failed: collisions.pk_hash

**Comment by ZigaMr** [comment]
Thats because of the SQL private key constraint, you already have the results for the collision saved in the DB. This is to prevent duplicated rows. Though I just pushed an update that also inserts new collisions if you change the iteration parameter which would generate new results on same address.

**Comment by alexxrobert** [comment]
i dont change anything, after a while i get these results, one ore more:
Gotem
ID: 1351911
Iteration: 1778
X: 1e81c336 Y: 6a7bf869
First: X: 0 Y: 3456086d
and then, just after check colisions, the scripts stops without any error.
and i need to delete database to start again with same wallet.

**Comment by alexxrobert** [comment]
oh, right iteration parameter, it was 2000 by default. so there is some aproximation of how many iterations are needed to find the key?

**Comment by ZigaMr** [comment]
Those are just some comments I had for debugging purpouses. The "Gotem" is actually printed from inside the openCL code, it means there was a collision with the 8byte uint, this happens frequently. When the openCL kernel stops execution (after 2000 iterations per thread) it then automatically checks if the collision is correct, so if you get no comments in the form of "private key: 0x...." it means the private key hasn't been found.

**Comment by ZigaMr** [comment]
Regarding approximating the iteration parameter, it depends on the length of the "vanity" part of the 20byte address. It has to do with binomial distribution, but basically the (in)equation looks like this:
k ≥ log(1 - C) / log(1 - p)
Where k is the number of runs, C is the desired % of certainty and p is the probability of generating the "vanity" part at random.
So for example in profanity the global size is set to 16384 * 255 = 4177920 times the iterations number, in this case 2000. So k = 8355840000 total runs, and lets say the vanity part is 5 hex characters long, which means p = 1/(16**5) = 9.5367431640625e-07.

If we plug in the numbers, lets say we want to be 99% certain, and probability p=1/(16**5). Then the equation looks like this:
log(1 - 0.99) / log(1 - 9.5367431640625e-07) = 4828868. So for vanity part of length 5, 2000 iterations is more than enough since total runs = 8355840000 which is a lot bigger than 4828868.

**Comment by g3troot** [comment]
I keep getting this error on startup. I tried installing libsecp256k1 manually following the instructions on the releases page on GitHub: https://github.com/bitcoin-core/secp256k1/releases

But now I don't understand how to use libsecp256k1 after building it?

Please tell me what am I doing wrong

```
D:\ReverseProfanityTool-main\seedFileGenerator>go run main.go
D:\ReverseProfanityTool-main\seedFileGenerator <nil>
panic: ScalarMult is not available when secp256k1 is built without cgo

goroutine 6 [running]:
github.com/ethereum/go-ethereum/crypto/secp256k1.(*BitCurve).ScalarMult(...)
        C:/Users/ASUS/go/pkg/mod/github.com/ethereum/go-ethereum@v1.12.0/crypto/secp256k1/scalar_mult_nocgo.go:13
github.com/ethereum/go-ethereum/crypto/secp256k1.(*BitCurve).ScalarBaseMult(...)
        C:/Users/ASUS/go/pkg/mod/github.com/ethereum/go-ethereum@v1.12.0/crypto/secp256k1/curve.go:251
main.PublicKeyFromSeed(0x8a060?)
        D:/ReverseProfanityTool-main/seedFileGenerator/main.go:53 +0x105
main.genSeedPublicKeysPerCpu(0x0?, 0x0, 0xfffffff, 0x0?)
        D:/ReverseProfanityTool-main/seedFileGenerator/main.go:85 +0x2cb
created by main.main
        D:/ReverseProfanityTool-main/seedFileGenerator/main.go:36 +0x187
exit status 2
```

**Comment by alexxrobert** [comment]
So the formula can be:
iterations = (log(1 - 0.99) / log(1 - 1/16**VANITY_CHARS))/4177920

**Comment by ZigaMr** [comment]
Yes that's correct.
